### ISSUE TITLE
Change re-entrancy settings to Pre-Allocated Clones

### ISSUE THREAD

**Issue by francois-normandin** [rfporter/Robust-CSV#2]
@rfporter If you get a chance to revisit this package, it would be nice to change the re-entrancy settings to Pre-Allocated clone and to flip the switch on "Separate compiled code from source file" too.

Goal: Accelerate parallel computation when running concurrent threads.

**Comment by rfporter** [comment]
Thanks. I didn't realize that it wasn't already marked as re-entrant. I will take care of it after the holidays.

**Comment by rfporter** [comment]
fixed in v1.2.0
